# Generated by Django 2.1.15 on 2020-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0002_pharmacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='deliver_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
