# Generated by Django 2.1.15 on 2020-06-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0003_auto_20200617_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('dob', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('phone', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('address', models.TextField(max_length=1000)),
                ('ip_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='IP Address')),
                ('pd_date', models.DateTimeField(null=True, verbose_name='Pickup Date')),
                ('pd_time', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], default='pickup', max_length=100)),
                ('zip', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('done', 'Pick Done')], default='pending', max_length=100)),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='Pick Done Date')),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy', to='pharmastore.Pharmacy')),
            ],
        ),
    ]
