# Generated by Django 2.1.15 on 2020-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0004_drugrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Pick Done')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
