# Generated by Django 2.1.15 on 2020-06-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0005_auto_20200617_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequest',
            name='country',
        ),
    ]
