# Generated by Django 2.1.15 on 2020-06-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0006_remove_drugrequest_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrequest',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy', to='pharmastore.Pharmacy'),
        ),
    ]
