# Generated by Django 2.1.15 on 2020-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0010_auto_20200618_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrequest',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
