# Generated by Django 2.1.15 on 2020-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0011_auto_20200618_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='deliver_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
