# Generated by Django 2.1.15 on 2020-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0012_auto_20200619_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrequest',
            name='pd_time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
