# Generated by Django 2.1.15 on 2020-06-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0013_auto_20200619_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='delivery',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=50, null=True),
        ),
    ]
