# Generated by Django 2.1.15 on 2020-06-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0014_auto_20200619_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresciptionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmastore.DrugRequest')),
            ],
        ),
    ]
