# Generated by Django 2.2 on 2020-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0016_auto_20200622_0536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresciptionImages',
        ),
    ]
